name: golang

on:
  push:
    branches: ["main"]

env:
  # The hostname used to communicate with the Redis service container
  REDIS_HOST: localhost
  # The default Redis port
  REDIS_PORT: 6379
jobs:
  build:
    runs-on:
      ubuntu-latest

      # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
          args: --verbose

      - name: Test
        run: go test -v ./...\

      - name: Build
        run: go build -v ./...
