name: golang

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
          args: --verbose

      - name: Test
        run: go test -v ./...\

      - name: Build
        run: go build -v ./...
